<a href="https://colab.research.google.com/github/tnwjd3315/daily-commit/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data import

In [40]:
import pandas as pd
import tensorflow as tf

In [41]:
# import data
path_lemonade = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
lemonade = pd.read_csv(path_lemonade)

path_boston= 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(path_boston)

path_iris = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path_iris)

In [42]:
print(lemonade.shape)
print(boston.shape)
print(iris.shape)

(6, 2)
(506, 14)
(150, 5)


In [43]:
print(lemonade.columns)
print(boston.columns)
print(iris.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [44]:
independent_lemonade = lemonade[['온도']]
dependent_lemonade = lemonade[['판매량']]
print(independent_lemonade.shape, dependent_lemonade.shape)

(6, 1) (6, 1)


In [45]:
independent_boston = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
dependent_boston = boston[['medv']]
print(independent_boston.shape, dependent_boston.shape)

(506, 13) (506, 1)


In [46]:
independent_iris = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent_iris = iris[['품종']]
print(independent_iris.shape, dependent_iris.shape)

(150, 4) (150, 1)


In [47]:
lemonade.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

Model Structure

In [51]:
# boston
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

Model Fit

In [52]:
model.fit(independent_boston, dependent_boston, epochs=5)

Epoch 1/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 38343.6484
Epoch 2/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 16925.7305
Epoch 3/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7553.3511
Epoch 4/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3131.4290
Epoch 5/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1044.5209


In [53]:
# 2. Structure through BatchNormalization layer
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [54]:
model.fit(independent_boston, dependent_boston, epochs=5)

Epoch 1/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 563.0114
Epoch 2/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 590.1537 
Epoch 3/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 579.1638
Epoch 4/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 560.4191
Epoch 5/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 512.8472


In [61]:
model.fit(independent_boston, dependent_boston, epochs=1000, verbose=0)
# model.fit(independent_boston, dependent_boston, epochs=10)

Use the model and predict

In [62]:
model.predict(independent_boston[5:10])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[27.30015 ],
       [21.404203],
       [20.38586 ],
       [16.458286],
       [20.24756 ]], dtype=float32)

In [66]:
dependent_boston[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [58]:
# check the model formel
print(model.get_weights())

[array([[ 2.2611460e-01, -1.6705415e-01,  1.2832759e-01,  3.4737352e-02,
         3.3380914e-01,  2.3420760e-01,  1.6451567e-01,  3.0017716e-01],
       [ 3.1962162e-01, -1.2559712e-01, -5.8816046e-01,  3.9580891e-01,
         3.9195007e-01,  7.6743211e-03,  3.7867852e-02,  2.2673121e-01],
       [ 3.6409053e-01,  2.7756605e-01, -4.6892947e-01, -4.8724058e-01,
         6.9257998e-01,  7.0749170e-01,  2.1552488e-02,  4.1218185e-01],
       [ 6.2684155e-01, -6.9153136e-01, -1.4301605e+00, -6.0916370e-01,
         3.4798738e-01, -7.9760873e-01, -9.3949676e-01,  3.6965051e-01],
       [-5.6875834e+00,  5.0242801e+00,  4.5482945e+00, -5.3555423e-01,
         7.4668002e-01,  6.2240887e-01,  3.4246342e+00, -1.3567491e+00],
       [-6.2303567e-01,  1.9655994e-01,  8.8999480e-01,  1.3900383e+00,
        -3.7708619e+00,  3.2059603e+00, -1.1319138e+00,  3.3581767e+00],
       [ 5.7732340e-02, -5.6638414e-01,  1.8096124e-01,  1.3000196e-01,
        -1.0578929e-01, -4.6667654e-02,  8.6681172e-02, -

Iris Classification by onehot-encoding (0 or 1)

In [73]:
# pd.get_dummies()
# activation = 'softmax' or 'sigmoid'
# loss='categorical_crossentropy' for classification
# loss='mse' for regression
# metrics='accuracy'

encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2       True          False         False
1   4.9  3.0    1.4   0.2       True          False         False
2   4.7  3.2    1.3   0.2       True          False         False
3   4.6  3.1    1.5   0.2       True          False         False
4   5.0  3.6    1.4   0.2       True          False         False

In [74]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [75]:
independent_iris = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent_iris = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent_iris.shape, dependent_iris.shape)

(150, 4) (150, 3)


In [81]:
# model structure
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',metrics=['accuracy'])

In [82]:
# model fit
model.fit(independent_iris, dependent_iris, epochs=200,verbose=0)

In [83]:
# use model
model.predict(independent_iris[0:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


array([[0.87257916, 0.06437329, 0.06304753],
       [0.86338705, 0.0779009 , 0.05871204],
       [0.84497523, 0.08034299, 0.07468181],
       [0.8049573 , 0.10141502, 0.09362767],
       [0.85738564, 0.06812665, 0.07448767]], dtype=float32)

In [85]:
print(dependent_iris[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0       True          False         False
1       True          False         False
2       True          False         False
3       True          False         False
4       True          False         False


In [86]:
# print the weight
model.get_weights()

[array([[ 0.69861686, -0.11925048, -0.5312374 ],
        [-0.30082375, -0.37633526,  0.31242552],
        [-0.74133885,  0.21914658,  0.32339987],
        [-1.5398968 ,  0.24271047,  0.70983   ]], dtype=float32),
 array([ 0.20366444,  0.33112225, -0.23859525], dtype=float32)]

Hidden Layers

In [87]:
# boston
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [88]:
model.summary()

Model: "functional_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_15 (InputLayer)     │ (None, 13)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 10)             │           140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_43 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 151 (604.00 B)

 Trainable params: 151 (604.00 B)

 Non-trainable params: 0 (0.00 B)

In [90]:
model.fit(independent_boston, dependent_boston, epochs=200,verbose=0)

In [91]:
print(model.predict(independent_boston[:5]))
print(dependent_boston[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
[[31.49887 ]
 [26.153473]
 [30.15316 ]
 [29.601334]
 [28.380592]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [93]:
# iris classification
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics=['accuracy'])

In [94]:
model.summary()

Model: "functional_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_17 (InputLayer)     │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_50 (Dense)                │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_51 (Dense)                │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 211 (844.00 B)

 Trainable params: 211 (844.00 B)

 Non-trainable params: 0 (0.00 B)

In [95]:
model.fit(independent_iris, dependent_iris, epochs=100,verbose=0)

In [96]:
print(model.predict(independent_iris[0:5]))
print(dependent_iris[0:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
[[9.9962103e-01 3.6028094e-04 1.8704064e-05]
 [9.9920076e-01 7.5706735e-04 4.2207019e-05]
 [9.9931753e-01 6.4222066e-04 4.0229250e-05]
 [9.9867451e-01 1.2643307e-03 6.1209626e-05]
 [9.9960321e-01 3.7755095e-04 1.9336947e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0       True          False         False
1       True          False         False
2       True          False         False
3       True          False         False
4       True          False         False


Better learning model

In [97]:
#X = tf.keras.layers.Input(shape=[13])
#H = tf.keras.layers.Dense(8, activation='swish')(X)
#H = tf.keras.layers.Dense(8, activation='swish')(H)
#H = tf.keras.layers.Dense(8, activation='swish')(H)
#Y = tf.keras.layers.Dense(1)(H)
#model = tf.keras.models.Model(X, Y)
#model.compile(loss='mse')

# BatchNormalization Layer
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [99]:
model.fit(independent_boston, dependent_boston, epochs=200,verbose=0)

In [100]:
print(model.predict(independent_boston[:5]))
print(dependent_boston[:5]) #much better!

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step
[[24.442066]
 [20.937023]
 [29.243473]
 [29.476198]
 [28.339901]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2
